version: '3.1'

services:
    # Databases # #
    db:
        image: postgres
        container_name: db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: movies
        ports:
            - 5432:5432
            
    # API # #
    api:
        container_name: api
        build: .
        ports:
            - 3000:3000
        volumes: 
            - .:/usr/src/app    

    
